### ISSUE TITLE
Add a version number to audit.dsk

### ISSUE THREAD

**Issue by tomcw** [zellyn/a2audit#2]
Can you add a version number to the audit.dsk?

When I run it from an Apple II (emulator), then I need to be able to see the version of the test suite. I can use this to compare and track any changes you make against current/future revisions of audit.dsk.

Thanks.

**Comment by zellyn** [comment]
https://github.com/zellyn/a2audit/commit/72aa7662237ccde81c4a79438be105506c1e970a

**Comment by tomcw** [comment]
Hi Zellyn,

Thanks for this and for the additional test (#3).

btw. I assume it's OK, but can I add your disk to my set of tests for AppleWin [here](https://github.com/AppleWin/AppleWin-Test)?
These tests are just used to check the builds before release - so are not part of the release package.

Thanks.

**Comment by zellyn** [comment]
@tomcw Sure, go ahead! And feel free to @ me on any AppleWin issues/bugs where it would have been helpful/appropriate to have had a check in a2audit :-)  The goal here is to let new emulators benefit from the years of bug finding that older emulators have had.
